spring.application.name=frauddetection

spring.datasource.url=jdbc:mysql://localhost:3306/frauddb
spring.datasource.username=root
spring.datasource.password=Meena@164


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8082
# Email details 
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=fraudalerts123@gmail.com

app.fraud.alert-recipient=fraudalerts123@gmail.com
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true












# admin12alerts@gmail.com======rzdmzegmkfqczehk  